In [10]:
import numpy as np
import pandas as pd

scores = np.random.randint(40,high=101,size=(50,5))
scores_df=pd.DataFrame(scores,
    columns=['國文','英文','數學','地理','歷史'],
    index=range(1,51))
scores_df.index.name="學號"
scores_df.columns.name="科目"

#display(sum_series)               #sum總分 #mean平均 #rank排名
sum_series=scores_df.sum(axis=1)
mean_series=scores_df.mean(axis=1)
rank_series=sum_series.rank(method='min',ascending=False) #rank依照總分1~50(但表格整體排列沒有變)
scores_df['總分']=sum_series
scores_df['平均']=mean_series
scores_df['名次']=rank_series
scores_df.sort_values(by="名次")   #sort_value把表格依照名次排列

科目   國文  英文  數學   地理   歷史   總分    平均    名次
學號
2    98  99  99   88   77  461  92.2   1.0
43   97  96  95   78   94  460  92.0   2.0
7   100  89  99  100   50  438  87.6   3.0
15   69  82  95   85   83  414  82.8   4.0
42   85  97  62   67  100  411  82.2   5.0
25   74  56  89   90   96  405  81.0   6.0
10   56  90  98   63   93  400  80.0   7.0
5    66  96  95   97   42  396  79.2   8.0
3    73  92  94   61   59  379  75.8   9.0
11   68  97  80   66   64  375  75.0  10.0
18   98  83  64   58   69  372  74.4  11.0
50   92  47  75   58   98  370  74.0  12.0
47   62  59  66   85   94  366  73.2  13.0
8    89  53  93   76   52  363  72.6  14.0
23   87  78  94   40   58  357  71.4  15.0
24   91  64  58   78   64  355  71.0  16.0
9    74  77  83   54   65  353  70.6  17.0
35   83  63  62   63   81  352  70.4  18.0
21   82  43  88   47   90  350  70.0  19.0
41   66  52  89   74   68  349  69.8  20.0
19   53  53  75   69   95  345  69.0  21.0
4    82  57  70   69   66  344  68.8  22.0
48   57  67  96   71   53  344  68.8  22.0
28   89  68  62   81   44  344  68.8  22.0
38   42  50  97   89   65  343  68.6  25.0
16   94  50  64   53   79  340  68.0  26.0
33   53  42  87   62   95  339  67.8  27.0
29   81  77  90   49   42  339  67.8  27.0
1    64  93  45   69   68  339  67.8  27.0
27   58  87  50   49   95  339  67.8  27.0
49   80  98  51   54   53  336  67.2  31.0
17   48  91  49   82   65  335  67.0  32.0
30   55  45  90   57   87  334  66.8  33.0
46   55  62  65   77   74  333  66.6  34.0
32   57  98  42   80   56  333  66.6  34.0
22   59  90  51   90   40  330  66.0  36.0
14   83  44  50   72   78  327  65.4  37.0
45   76  64  44   76   67  327  65.4  37.0
6    74  69  53   80   49  325  65.0  39.0
34   40  80  63   77   65  325  65.0  39.0
13   59  41  89   82   48  319  63.8  41.0
31   56  40  76   78   62  312  62.4  42.0
12   59  65  69   59   56  308  61.6  43.0
26   70  83  67   43   45  308  61.6  43.0
36   61  51  66   50   57  285  57.0  45.0
37   52  55  87   48   41  283  56.6  46.0
40   70  40  47   46   80  283  56.6  46.0
20   79  42  49   58   53  281  56.2  48.0
44   40  83  46   44   56  269  53.8  49.0
39   42  42  50   42   91  267  53.4  50.0

In [11]:
#如何在既有表格加一欄，產生新的表格
display(scores_df.iloc[:3])  #[]預設抓欄、抓列要用iloc 
new_df = scores_df.iloc[:3].copy()
new_df["不及格"] = pd.Series ([1,0,2],index=[1,2,3])  #自己算，比較笨的方式
new_df

科目  國文  英文  數學  地理  歷史   總分    平均    名次
學號
1   64  93  45  69  68  339  67.8  27.0
2   98  99  99  88  77  461  92.2   1.0
3   73  92  94  61  59  379  75.8   9.0

科目  國文  英文  數學  地理  歷史   總分    平均    名次  不及格
學號
1   64  93  45  69  68  339  67.8  27.0    1
2   98  99  99  88  77  461  92.2   1.0    0
3   73  92  94  61  59  379  75.8   9.0    2

In [12]:
def func3(series:pd.Series) -> int:
    return series[series<=60].count()   #count統計數量，不用自己算
less60Count = scores_df[['國文','英文','數學','地理','歷史']].apply(func3,axis=1)#apply預設是抓直的欄
less60Count

學號
1     1
2     0
3     1
4     1
5     1
6     2
7     1
8     2
9     1
10    1
11    0
12    3
13    3
14    2
15    0
16    2
17    2
18    1
19    2
20    4
21    2
22    3
23    2
24    1
25    1
26    2
27    3
28    1
29    2
30    3
31    2
32    3
33    2
34    1
35    0
36    3
37    4
38    2
39    4
40    3
41    1
42    0
43    0
44    4
45    1
46    1
47    1
48    2
49    3
50    2
dtype: int64

In [13]:
scores_df['不及格']=less60Count
scores_df

科目   國文  英文  數學   地理   歷史   總分    平均    名次  不及格
學號
1    64  93  45   69   68  339  67.8  27.0    1
2    98  99  99   88   77  461  92.2   1.0    0
3    73  92  94   61   59  379  75.8   9.0    1
4    82  57  70   69   66  344  68.8  22.0    1
5    66  96  95   97   42  396  79.2   8.0    1
6    74  69  53   80   49  325  65.0  39.0    2
7   100  89  99  100   50  438  87.6   3.0    1
8    89  53  93   76   52  363  72.6  14.0    2
9    74  77  83   54   65  353  70.6  17.0    1
10   56  90  98   63   93  400  80.0   7.0    1
11   68  97  80   66   64  375  75.0  10.0    0
12   59  65  69   59   56  308  61.6  43.0    3
13   59  41  89   82   48  319  63.8  41.0    3
14   83  44  50   72   78  327  65.4  37.0    2
15   69  82  95   85   83  414  82.8   4.0    0
16   94  50  64   53   79  340  68.0  26.0    2
17   48  91  49   82   65  335  67.0  32.0    2
18   98  83  64   58   69  372  74.4  11.0    1
19   53  53  75   69   95  345  69.0  21.0    2
20   79  42  49   58   53  281  56.2  48.0    4
21   82  43  88   47   90  350  70.0  19.0    2
22   59  90  51   90   40  330  66.0  36.0    3
23   87  78  94   40   58  357  71.4  15.0    2
24   91  64  58   78   64  355  71.0  16.0    1
25   74  56  89   90   96  405  81.0   6.0    1
26   70  83  67   43   45  308  61.6  43.0    2
27   58  87  50   49   95  339  67.8  27.0    3
28   89  68  62   81   44  344  68.8  22.0    1
29   81  77  90   49   42  339  67.8  27.0    2
30   55  45  90   57   87  334  66.8  33.0    3
31   56  40  76   78   62  312  62.4  42.0    2
32   57  98  42   80   56  333  66.6  34.0    3
33   53  42  87   62   95  339  67.8  27.0    2
34   40  80  63   77   65  325  65.0  39.0    1
35   83  63  62   63   81  352  70.4  18.0    0
36   61  51  66   50   57  285  57.0  45.0    3
37   52  55  87   48   41  283  56.6  46.0    4
38   42  50  97   89   65  343  68.6  25.0    2
39   42  42  50   42   91  267  53.4  50.0    4
40   70  40  47   46   80  283  56.6  46.0    3
41   66  52  89   74   68  349  69.8  20.0    1
42   85  97  62   67  100  411  82.2   5.0    0
43   97  96  95   78   94  460  92.0   2.0    0
44   40  83  46   44   56  269  53.8  49.0    4
45   76  64  44   76   67  327  65.4  37.0    1
46   55  62  65   77   74  333  66.6  34.0    1
47   62  59  66   85   94  366  73.2  13.0    1
48   57  67  96   71   53  344  68.8  22.0    2
49   80  98  51   54   53  336  67.2  31.0    3
50   92  47  75   58   98  370  74.0  12.0    2