In [4]:
import numpy as np
import pandas as pd
scores=np.random.randint(50,100,size=(50,5)) 
scores_df=pd.DataFrame(scores,
            columns=['國文','英文','數學','地理','歷史'],
            index=range(1,51))
scores_df
sum_values=scores_df.sum(axis=1)
mean_values=scores_df.mean(axis=1)
scores_df['總分']=sum_values
scores_df['平均']=mean_values

In [10]:
scores_df.sort_values(by='總分',ascending=False).iloc[:5] #ascending由小變大，#ascending=False由大變小

    國文  英文  數學  地理  歷史   總分    平均
11  98  89  89  64  90  430  86.0
39  66  93  89  97  77  422  84.4
3   50  75  97  99  96  417  83.4
34  98  73  56  96  91  414  82.8
5   88  72  96  60  94  410  82.0

In [15]:
#使用subscript[],過濾資料
scores_df[scores_df['平均']<80]   #series陣列運算可用加減乘除，比較運算子<產生布林值 true、false

    國文  英文  數學  地理  歷史   總分    平均
1   76  61  69  87  66  359  71.8
2   99  75  62  66  87  389  77.8
4   67  77  61  78  59  342  68.4
6   83  52  51  72  70  328  65.6
8   56  82  80  81  99  398  79.6
9   64  75  99  61  62  361  72.2
12  60  85  63  65  88  361  72.2
13  82  92  76  73  70  393  78.6
14  55  52  87  71  88  353  70.6
15  83  63  73  85  52  356  71.2
16  83  97  69  50  58  357  71.4
17  67  74  74  58  70  343  68.6
18  88  58  88  98  61  393  78.6
19  92  59  65  57  57  330  66.0
20  67  68  68  83  76  362  72.4
21  64  83  77  99  50  373  74.6
22  56  72  81  53  61  323  64.6
24  77  72  62  86  60  357  71.4
25  53  51  93  64  63  324  64.8
26  84  68  92  58  89  391  78.2
27  57  63  65  59  52  296  59.2
28  56  61  92  77  99  385  77.0
29  60  61  76  76  84  357  71.4
30  63  78  77  73  51  342  68.4
31  52  97  71  78  98  396  79.2
32  75  58  66  75  62  336  67.2
33  61  85  70  91  66  373  74.6
36  74  93  71  50  67  355  71.0
37  82  78  65  81  72  378  75.6
38  58  57  56  99  67  337  67.4
40  70  80  61  99  59  369  73.8
41  75  61  93  63  95  387  77.4
42  57  68  81  60  52  318  63.6
44  53  90  55  54  75  327  65.4
45  53  70  97  50  78  348  69.6
46  55  62  89  97  70  373  74.6
47  83  63  52  60  57  315  63.0
48  80  82  56  60  77  355  71.0
49  78  55  63  79  63  338  67.6
50  69  50  66  78  87  350  70.0